<a href="https://colab.research.google.com/github/HusanboyMuminov/ai_foundation/blob/main/students_performance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
!pip install pandas numpy

In [9]:
import pandas as pd
import numpy as np

In [20]:
df = pd.read_csv("student_performance.csv")

print("Dataset shape (rows, columns):", df.shape)
print("Column name:", df.columns.tolist())

print("First 5 rows of the dataset:")
print(df.head())

print("Summary statistics:")
print(df.describe())

print("Data types and null info:")
print(df.info())

Dataset shape (rows, columns): (1000000, 6)
Column name: ['student_id', 'weekly_self_study_hours', 'attendance_percentage', 'class_participation', 'total_score', 'grade']
First 5 rows of the dataset:
   student_id  weekly_self_study_hours  attendance_percentage  \
0           1                     18.5                   95.6   
1           2                     14.0                   80.0   
2           3                     19.5                   86.3   
3           4                     25.7                   70.2   
4           5                     13.4                   81.9   

   class_participation  total_score grade  
0                  3.8         97.9     A  
1                  2.5         83.9     B  
2                  5.3        100.0     A  
3                  7.0        100.0     A  
4                  6.9         92.0     A  
Summary statistics:
           student_id  weekly_self_study_hours  attendance_percentage  \
count  1000000.000000           1000000.000000      

In [22]:
print("Average score by columns:")

print(df.mean(numeric_only=True))

Average score by columns:
student_id                 500000.500000
weekly_self_study_hours        15.029127
attendance_percentage          84.711046
class_participation             5.985203
total_score                    84.283845
dtype: float64


In [23]:
print("Average score by columns:")

print(df.max(numeric_only=True))

Average score by columns:
student_id                 1000000.0
weekly_self_study_hours         40.0
attendance_percentage          100.0
class_participation             10.0
total_score                    100.0
dtype: float64


In [24]:
print("Average score by columns:")

print(df.min(numeric_only=True))

Average score by columns:
student_id                  1.0
weekly_self_study_hours     0.0
attendance_percentage      50.0
class_participation         0.0
total_score                 9.4
dtype: float64


In [25]:
# Correlation
print("Correlation:")

print(df.corr(numeric_only=True))

Correlation:
                         student_id  weekly_self_study_hours  \
student_id                 1.000000                -0.001607   
weekly_self_study_hours   -0.001607                 1.000000   
attendance_percentage     -0.000353                -0.001008   
class_participation        0.001277                 0.001244   
total_score               -0.000492                 0.812241   

                         attendance_percentage  class_participation  \
student_id                           -0.000353             0.001277   
weekly_self_study_hours              -0.001008             0.001244   
attendance_percentage                 1.000000            -0.000043   
class_participation                  -0.000043             1.000000   
total_score                          -0.001014             0.000684   

                         total_score  
student_id                 -0.000492  
weekly_self_study_hours     0.812241  
attendance_percentage      -0.001014  
class_participation

In [29]:
df["total score"] = df[["class_participation", "weekly_self_study_hours", "attendance_percentage"]].sum(axis=1)
df["average score"] =df["total score"] / 3
df["passed"] = np.where(df["average score"] >= 50, "Yes", "No")

print("New columns preview (total, average, passed):")
print(df[["total score",  "average score", "passed"]].head())

New columns preview (total, average, passed):
   total score  average score passed
0        117.9      39.300000     No
1         96.5      32.166667     No
2        111.1      37.033333     No
3        102.9      34.300000     No
4        102.2      34.066667     No


In [35]:
test_prep_group = df.groupby('student_id')[["class_participation", "weekly_self_study_hours", "attendance_percentage"]].mean()
print("student score by test preparation course:")
print(test_prep_group)

# Class-based average
gender_avg = df.groupby("class_participation")[["total_score", "weekly_self_study_hours", "attendance_percentage"]].mean()
print("Average score by gender:")
print(gender_avg)

student score by test preparation course:
            class_participation  weekly_self_study_hours  \
student_id                                                 
1                           3.8                     18.5   
2                           2.5                     14.0   
3                           5.3                     19.5   
4                           7.0                     25.7   
5                           6.9                     13.4   
...                         ...                      ...   
999996                      4.8                     18.0   
999997                      6.7                     15.7   
999998                      5.8                     14.2   
999999                      5.3                     25.3   
1000000                     4.1                     18.3   

            attendance_percentage  
student_id                         
1                            95.6  
2                            80.0  
3                            86.3

In [39]:
# Convert scores to Numpy array
scores = df[["total_score", "weekly_self_study_hours", "attendance_percentage"]].values

# Mean, Std Deviation
print("Numpy Mean:", np.mean(scores, axis=0))
print("Numpy Std:", np.std(scores, axis=0))

# Z-score (normalize)
z_score = (scores - np.mean(scores, axis=0)) / np.std(scores, axis=0)
print("Z-scores (normalized numbers)")
print(z_score[:5])
# Average 0
# Negative -
# Positive +

Numpy Mean: [84.2838453 15.0291269 84.711046 ]
Numpy Std: [15.43296106  6.89942757  9.42413867]
Z-scores (normalized numbers)
[[ 0.88227753  0.50306682  1.15543228]
 [-0.02487179 -0.1491612  -0.49989141]
 [ 1.01834992  0.64800638  0.16860469]
 [ 1.01834992  1.54663166 -1.53977424]
 [ 0.49997889 -0.23612494 -0.29828148]]


In [40]:
# How many students scored above 90 average ?
top_scorers = df[df["average score"] >=90]
print("Top scored student above 90:", len(top_scorers))

# How many failed?
failed = df[df["passed"] == "No"]
print("Failed from exam:", len(failed))

Top scored student above 90: 0
Failed from exam: 999999
